### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by apeltzer**
Found by @ameynert right now 🚨

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/scrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by grst — APPROVED** [review]
Oops

**Comment by apeltzer** [comment]
@nf-core-bot fix linting

**Review by ameynert — CHANGES_REQUESTED** [review]
Pipeline test runs are failing - can't find FASTQ files.

**Comment by apeltzer** [comment]
No idea whats the problem here - anyone see the error? @grst @ameynert ?

**Comment by grst** [comment]
Doesn't look wrong? Does it work locally? 

To debug, you could try uploading artifacts with the `.nextflow.log` and the `work` directory, as done in modules: 
https://github.com/nf-core/modules/blob/36a77f7c6decf2d1fb9f639ae982bc148d6828aa/.github/workflows/pytest-workflow.yml#L91-L108

**Review by ameynert — APPROVED** [review]
LGTM!

**Pull request merged**
