### PR TITLE
Fix dependencies, but waiting for feedback on tximeta first

### PR DESCRIPTION
**Pull request by apeltzer**
Lets see if this updates all nicely and builds a proper container - i fear not :-(

### CODE REVIEW

**Comment by apeltzer** [comment]
Yeah, its the environment again. @sk-sahu @ggabernet - not sure how we can solve this, see also @sk-sahu PR #47 for a description of the issue here 😓

**Comment by ggabernet** [comment]
Maybe directly porting it to dsl2? I ended up doing this for bcellmagic as I had lots of conflicts and spent like 2 full days trying to solve them...

**Comment by sk-sahu** [comment]
Pushed a hacky solution https://github.com/nf-core/scrnaseq/pull/47/commits/9d38639d51e88ebb4fbe9b466d85744b88316bd0 which is working for now via container. Tested locally.

**Comment by apeltzer** [comment]
Thanks for the feedback, lets keep @sk-sahu fix & not do this anymore as we're moving to DSLv2.

**Pull request closed without merging**
