### PR TITLE
Remove universc subworkflow from pipeline

### PR DESCRIPTION
**Pull request by fmalmeida**
# About

Opening a PR to address #289 . Decision was made to remove `universc` from pipeline since it was broke for quite a while and there was no request for fixing it during period.

## PR checklist

- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by fmalmeida** [comment]
Hi @grst ,
If I understand correctly, the work on #289 would be addressed by what it is in this PR.

There is one thing though, we need to remove the universc information from the metromap.

Do you know who has created the metromap, or, are you able to quickly modify it?

**Comment by grst** [comment]
Well the SVG is here: https://github.com/nf-core/scrnaseq/blob/master/docs/images/rnaseq_pipeline_V1.0-metro_clean.svg

**Comment by fmalmeida** [comment]
Hi @grst ,
Upon checking, it seems we already have a PNG without `universc`, but maybe was never migrated to use it:

https://github.com/nf-core/scrnaseq/blob/289-update-or-remove-universc/docs/images/scrnaseq_pipeline_v2.0_metro_clean.png

Probably we should just update the documentation to use it since it has the other included workflows.

One problem is that it does not have an SVG included.

Another point is, should the v1-0 files be removed?

**Comment by fmalmeida** [comment]
Actually, now looking at it, it seems some changes from it where never integrated.

**Comment by grst** [comment]
like, scATAC?

**Comment by fmalmeida** [comment]
Hi @grst ,
Do you think these are good enough for the release, but then we have to create an issue to try to properly address it in the next hackathon?

scrnaseq_pipeline_v1 0_metro_clean
srnaseq_pipeline_V3 0-metro_clean

**Comment by grst** [comment]
that's fine with me!

**Comment by fmalmeida** [comment]
Should then be ready for review, @grst

**Review by grst — APPROVED** [review]
Some tests are failing, other than that LGTM!

**Comment by fmalmeida** [comment]
> Some tests are failing, other than that LGTM!

not sure why they failed, as there was no change to the processings :/

**Comment by fmalmeida** [comment]
> Some tests are failing, other than that LGTM!

Hi @grst ,
The error on the tests are the java version. Do you know where we can change it?

```console
Run nf-core/setup-nextflow@v2
Input version 'latest-everything' resolved to Nextflow v24.11.0-edge
Downloaded `nextflow` to /opt/hostedtoolcache/nextflow/24.11.0-edge/x64 and added to PATH
(node:83297) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/hostedtoolcache/nextflow/24.11.0-edge/x64/nextflow help
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 17 or later (up to [23](https://github.com/nf-core/scrnaseq/actions/runs/12139073488/job/33853897755?pr=396#step:6:24)) is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /usr/lib/jvm/temurin-11-jdk-amd64/bin/java
 JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64
```

**Comment by grst** [comment]
See https://nfcore.slack.com/archives/CE6SDBX2A/p1733269671253319

**Pull request merged**
