### PR TITLE
Fix 263

### LINKED ISSUE #263: Fix whitelist logic for Drop-seq
### Description of the bug

We tried to run the scrnaseq workkflow on some Drop-seq data, but it crashed with this error:
``` 
gzip: invalid magic
```
Looking at this a bit more closely, this was the command that caused it:

```
# run simpleaf quant
gzip -dcf  > whitelist.uncompressed.txt
```
https://github.com/nf-core/scrnaseq/blob/61d1919aa96a4d82517aeb6d04943262a42a055e/modules/local/simpleaf_quant.nf#L57

Before running `SIMPLEAF_QUANT`, it attempts to uncompress a non-existent file. In other words, for any method that doesn't provide a whitelist of possible barcodes (such as Drop-seq), as it stands the `scrnaseq` workflow will fail by design. 

```nextflow
if (params.barcode_whitelist) {
    ch_barcode_whitelist = file(params.barcode_whitelist)
} else if (params.protocol.contains("10X")) {
    ch_barcode_whitelist = file("$baseDir/assets/whitelist/10x_${chemistry}_barcode_whitelist.txt.gz", checkIfExists: true)
} else {
    ch_barcode_whitelist = [] // THIS LOGIC NEEDS FIXING
}
```

https://github.com/nf-core/scrnaseq/blob/61d1919aa96a4d82517aeb6d04943262a42a055e/workflows/scrnaseq.nf#L82

### TEMPORARY REMEDY
As the `gzip` command is hard-coded into the script block (see above), the only way to get it to not fail is by staging a gzip compressed file via the whitelist option (I uploaded an empty file to S3):

```
gzip -dcf empty_gzip_file.txt.gz > whitelist.uncompressed.txt
```
One can then get `simpleaf_quant` to infer the confident barcodes, e.g. via the `--knee` method (thanks to @rob-p for advice!). This will then skip adding the (non-existent) whitelist to the `simpleaf_quant` command, achieved here:
https://github.com/nf-core/scrnaseq/blob/61d1919aa96a4d82517aeb6d04943262a42a055e/modules/local/simpleaf_quant.nf#L34

Lastly, I had to pass the following external arguments to `simpleaf_quant` to use the knee argument as well as a resolution method how near-duplicate UMIs are resolved. 
(quoting Rob:
> The `cr-like` method is a safe default I think. That is, it’s not just meant for chromium chemistries, but is a general algorithm.  In general, I think the specific method by which similar UMIs should be allocated is still an active area of research.)

Adding the following to the Nextflow config allowed the job to complete successfully:

```nextflow
withName:'SIMPLEAF_QUANT'{
    ext.args = "--knee -r cr-like"
}
```

Thanks, Felix

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by grst**
Fixes #263 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/scrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by grst** [comment]
@FelixKrueger, could you please give this a try?

**Review by fmalmeida — APPROVED** [review]
Looks good and clean.

**Comment by FelixKrueger** [comment]
I can confirm that whitelist logic fix works on our data for a test run, will be good to integrate this into main for the next release. Cheers!

**Comment by grst** [comment]
Should already be in 2.4.1 :)

**Pull request merged**
