### PR TITLE
Add genomic feature and barcode length option for STAR

### PR DESCRIPTION
**Pull request by Vivian-chen16**
(1) Current `--aligner star` does not include`--soloBarcodeReadLength` in the executed command and it leads to `FATAL ERROR` once the barcode length is not equal to default value 26. This can be resolved with additional parameter to parse customized length in. 
(2) `--include-introns` is now set by default on CellRanger v7.0 and thus it could be useful to have `--soloFeatures` as a new star option to align the output from CellRanger.
(3) According to `STARsolo.md`, it is recommended to have: `--clipAdapterType CellRanger4 --outFilterScoreMin 30
--soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts --soloUMIfiltering MultiGeneUMI_CR --soloUMIdedup 1MM_CR` for the best match to CellRanger >= 4.0. (https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md)

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

### CODE REVIEW

**Comment by grst** [comment]
Thanks for putting together this PR! 

We are happy to discuss what sensible defaults are for starsolo, and the current version is quite likely not optimal. 
However, there are a few things that would need to be discussed and potentially solved differently before this can be merged: 

1. The barcode length differs depending on the 10x chenistry version. All options related to the chemistry are getting resolved in [`WorkflowScrnaseq.groovy`](https://github.com/nf-core/scrnaseq/blob/master/lib/WorkflowScrnaseq.groovy). Actually I'm surprised that setting `--soloType $chemistry` doesn't correctly set the correct default barcode length?

2. Any option that we don't want to set on a per-sample basis (`--soloFeatures` probably) should get into the module via `task.ext.args` rather than an input channel. This makes it easy to override these options through a config file.  

3. While it would be nice to have an option to make Starsolo behave as similarly as possible to cellranger, I'm not sure I would make this the default option. But maybe we can have a preset that sets the corresponding options automatically? Happy to hear what others think. 

Cheers, 
Gregor

**Comment by wpoehlm** [comment]
Hi @grst,

Fair points! Just to add a bit of context to our motivation for these suggested changes:

1. We have found that, for starsolo, the workflow fails if we do not specify the correct barcode length. Could this be a bug in the pipeline?
2. We've done some benchmarking between StarSolo and CellRanger and generally found that the results are similar. However, if you align to introns for single-cell datasets (as is default for CellRanger), the results are not so similar. Thus, we think that this default option should be used with caution, and it would be beneficial to make it an explicit input for users. In addition, it is preferable to have this option as a workflow parameter for users of graphical interfaces such Nextflow Tower where it isn't as easy to modify the module configuration. 
3. I tend to agree with you that it might not be the best to have these customizations as the default, especially as cellranger evolves. The preset idea sounds like a good solution to me

**Comment by apeltzer** [comment]
Hi @wpoehlm and @Vivian-chen16 !

Thanks for the PR, regarding your questions @wpoehlm 

1.) yes, could be. Also that part of the pipeline didn't receive frequent updates lately so could also be out-of-date as the sc analysis ecosystem moves quickly.
2.) Regarding making the option available as a configurable one, I absolutely agree and think this is a good idea. Changing to a different default, I'm a bit more concerned/cautious though not really heavily opinionated. 
3.) Preset sounds great!

**Comment by apeltzer** [comment]
Hi @Vivian-chen16 - could you find some time to adding  the chemistry related parts on this PR? That would be great and we can then merge this to `dev` to have at least the functionality in 2.1.0 integrated that most people would see as the consensus :-)

**Comment by Vivian-chen16** [comment]
Hi all,

since this PR may need further discussion and it's actually outdated, I'm going to open separate issues for each feature instead for better tracking and close this one. Please feel free to comment if there's other thought or concern.

**Pull request closed without merging**
