### PR TITLE
Integrate Cellranger-atac

### PR DESCRIPTION
**Pull request by heylf**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/scrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by heylf** [comment]
Currently the modules are local. PR for nf-core modules are in place already: https://github.com/nf-core/modules/pull/2450

**Comment by heylf** [comment]
Should I include an individual test for cellranger-atac? Because cellranger-atac needs different type of data and input format.

**Comment by apeltzer** [comment]
In such a case definitely some extra test profile + test data is justified 👍🏻

**Comment by apeltzer** [comment]
And in general: More tests do not hurt ;-)

**Comment by heylf** [comment]
@nf-core-bot fix linting

**Comment by heylf** [comment]
I am not sure why the test fails because it works for me locally.

**Comment by heylf** [comment]
Waiting for test data to arrive in the nf-core https://github.com/nf-core/test-datasets/pull/687

**Comment by heylf** [comment]
Pipeline misses right now a container that has scanpy and muon (needed for mtx_to_h5ad)

**Comment by apeltzer** [comment]
Can you attempt at fixing the conflicts so this can be merged soon @heylf ?

**Comment by klkeys** [comment]
> Waiting for test data to arrive in the nf-core [nf-core/test-datasets#687](https://github.com/nf-core/test-datasets/pull/687)

that pull is obselete and unmerged, leaving note here about suitable nad successfully merged test data in https://github.com/nf-core/test-datasets/pull/847

**Pull request closed without merging**
